import supabase from '../config/supabase.js';
import env from '../config/env.js';
import { AppError } from '../middleware/errorHandler.js';

/**
 * Uploads an in-memory audio Buffer to Supabase Cloud Storage.
 * @param {Buffer} audioBuffer - The binary MP3 buffer generated by the TTS engine
 * @param {string} mimeType - The MIME type (default 'audio/mpeg')
 * @returns {Promise<{ fileName: string, publicUrl: string, size: number }>}
 */
export async function uploadAudioBuffer(audioBuffer, mimeType = 'audio/mpeg') {
    try {
        if (!audioBuffer || !Buffer.isBuffer(audioBuffer)) {
            throw new AppError('Invalid audio buffer provided for upload.', 400, 'INVALID_BUFFER');
        }

        // Generate unique, collision-proof filename with timestamp
        const uniqueSuffix = `${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
        const fileName = `speech-${uniqueSuffix}.mp3`;

        // Upload directly to Supabase Storage bucket
        const { data, error } = await supabase.storage
            .from(env.SUPABASE_STORAGE_BUCKET)
            .upload(fileName, audioBuffer, {
                contentType: mimeType,
                cacheControl: '3600',
                upsert: false,
            });

        if (error) {
            console.error('❌ Supabase Upload Error:', error.message);
            throw new AppError(`Failed to save audio file to cloud storage: ${error.message}`, 502, 'STORAGE_UPLOAD_FAILED');
        }

        // Retrieve the permanent public URL
        const { data: urlData } = supabase.storage
            .from(env.SUPABASE_STORAGE_BUCKET)
            .getPublicUrl(fileName);

        return {
            fileName,
            publicUrl: urlData.publicUrl,
            size: audioBuffer.length,
        };
    } catch (err) {
        if (err instanceof AppError) throw err;
        throw new AppError(`Storage service error: ${err.message}`, 500, 'STORAGE_SERVICE_ERROR');
    }
}

/**
 * Deletes an audio file from storage (cleanup helper).
 */
export async function deleteAudioFile(fileName) {
    try {
        const { error } = await supabase.storage.from(env.SUPABASE_STORAGE_BUCKET).remove([fileName]);
        if (error) {
            console.warn(`⚠️ Could not delete file "${fileName}":`, error.message);
            return false;
        }
        return true;
    } catch (err) {
        console.warn(`⚠️ Error in deleteAudioFile:`, err.message);
        return false;
    }
}

export default {
    uploadAudioBuffer,
    deleteAudioFile,
};